name: test

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1.3.1
      - name: build release
        run:  msbuild msvc2022\oblast.sln -t:rebuild -verbosity:quiet -property:Configuration=Release
      - name: test
        run:  bin\Release\gem.exe >bin\Release\gem.test.txt 2>&1
      - name: upload test result
        uses: actions/upload-artifact@v3
        with:
          name: test results
          path: |
            bin\Release\gem.test.txt
          retention-days: 14
